### ISSUE TITLE
New tracks

### ISSUE THREAD

**Issue by cecilevdwaal** [schuifel-shuffle/schuifel-shuffle-data#3]
Sting - Shape of my heart - https://open.spotify.com/track/1ZXfToGBX4iSwghR23xf1h?si=gPmf2JHDQZ-xxzv67Lbu2g 
Jewel - You were meant for me - https://open.spotify.com/track/6kBU9uWqar0Fw2Ws0he11A?si=rCzIljvYQxOPi79uDwGhjw 
Christina Aguilera - Hurt https://open.spotify.com/track/6gDXbcILAyBa2skSdbUYq7?si=IMUO-XGUTFGu21q1HNhtbg 
Ed Sheeran - Perfect https://open.spotify.com/track/0tgVpDi06FyKpA1z0VMD4v?si=suhE1qncTgecN0CpSpYxqw 
Johnny Cash - Hurt https://open.spotify.com/track/28cnXtME493VX9NOw9cIUh?si=ZeEopdiiT6SFTYVI0cMmAg 
Rod Stewart - The Way You Look Tonight https://open.spotify.com/track/7hP1DiP1l4y2zU5HxurVo3?si=jdyMjF_3SoifOj9a1SS66Q

**Comment by rvanlaarhoven** [comment]
Not sure about the Johnny Cash one yet actually.. What do you think @schuifel-shuffle/voters ?

**Comment by luukjanssens** [comment]
Haha, Shape of my Heart, cllllassic!! I think that Cash track is quite dark for an intense Schuifel moment. That said, maybe that Jewel song is a bit too country, rhythm-wise?

**Comment by cecilevdwaal** [comment]
Haha yes, Cash is a bit depressing

**Comment by WoutGroenendijk** [comment]
Johnny Cash is way too dark!

https://www.youtube.com/watch?v=g4ChTL-3c3o
